# ServiceMonitor para Prometheus
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: websocket-service-monitor
  labels:
    app: websocket-service
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: websocket-service
  endpoints:
    - port: websocket
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
    - port: websocket
      path: /health
      interval: 30s
      scrapeTimeout: 5s
---
# ServiceMonitor para Redis
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-cluster-monitor
  labels:
    app: redis-cluster
    monitoring: prometheus
spec:
  selector:
    matchLabels:
      app: redis-cluster
  endpoints:
    - port: client
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
---
# PodMonitor para métricas detalhadas dos pods
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: websocket-pod-monitor
  labels:
    app: websocket-service
spec:
  selector:
    matchLabels:
      app: websocket-service
  podMetricsEndpoints:
    - port: websocket
      path: /metrics
      interval: 15s
---
# PrometheusRule para alertas
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: websocket-alerts
  labels:
    app: websocket-service
    monitoring: prometheus
spec:
  groups:
    - name: websocket.rules
      rules:
        # Alert para alta utilização de CPU
        - alert: WebSocketHighCPU
          expr: rate(container_cpu_usage_seconds_total{pod=~"websocket-service-.*"}[5m]) * 100 > 80
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "WebSocket pod {{ $labels.pod }} high CPU usage"
            description: "WebSocket pod {{ $labels.pod }} CPU usage is {{ $value }}%"

        # Alert para alta utilização de memória
        - alert: WebSocketHighMemory
          expr: container_memory_usage_bytes{pod=~"websocket-service-.*"} / container_spec_memory_limit_bytes{pod=~"websocket-service-.*"} * 100 > 85
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "WebSocket pod {{ $labels.pod }} high memory usage"
            description: "WebSocket pod {{ $labels.pod }} memory usage is {{ $value }}%"

        # Alert para pods não saudáveis
        - alert: WebSocketPodNotReady
          expr: kube_pod_status_ready{pod=~"websocket-service-.*", condition="false"} == 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "WebSocket pod {{ $labels.pod }} not ready"
            description: "WebSocket pod {{ $labels.pod }} has been not ready for more than 1 minute"

        # Alert para Redis cluster não saudável
        - alert: RedisClusterNotHealthy
          expr: up{job="redis-cluster"} == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Redis cluster node down"
            description: "Redis cluster node {{ $labels.instance }} is down"