apiVersion: v1
kind: Service
metadata:
  name: websocket-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 1800
  ports:
    - port: 9002
      targetPort: 9002
  selector:
    app: websocket