apiVersion: v1
kind: Service
metadata:
  name: websocket-service
  labels:
    app: websocket-service
spec:
  type: ClusterIP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 3600  # 1 hora
  ports:
    - port: 9002
      targetPort: 9002
      protocol: TCP
      name: websocket
  selector:
    app: websocket-service