apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-scripts
data:
  01-create-messages-table.sql: |
    -- Create messages table for chat application
    CREATE TABLE IF NOT EXISTS messages (
      id SERIAL PRIMARY KEY,
      user_id INTEGER NOT NULL,
      content TEXT NOT NULL,
      timestamp TIMESTAMPTZ NOT NULL DEFAULT now()
    );
    
    -- Create index for faster queries
    CREATE INDEX IF NOT EXISTS idx_messages_timestamp ON messages(timestamp);
    CREATE INDEX IF NOT EXISTS idx_messages_user_id ON messages(user_id);
    
    -- Insert some sample data for testing
    INSERT INTO messages (user_id, content, timestamp) VALUES 
    (1, 'Hello, this is a test message!', now()),
    (2, 'Welcome to the chat application!', now()),
    (1, 'How is everyone doing today?', now())
    ON CONFLICT DO NOTHING;